site: Gesko
url: #yoururl
title: P0WEX
description: >-
  just a minimalist, personal blog
googlewebfonts: Fira+Code:wght@400;500;700
twitter:
  username: #yourusername
  card: 
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourname
  avatar: #youravatar
  email: #youremail
  url: #yoururl
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  - scope:
    path: ""
    values:
    layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
    path: ""
    type: "posts"
    values:
    layout: "post"

relative_links:
  enabled:     true
  collections: false


