site: blahaj.life
title: ptrpaws's blog 🌸
description: |-
  Hey, I'm <a href="https://twitter.com/ptrpaws">Ellie</a> and 21 y/o!
  And this is my blog on reverse engineering, programming, vr finds and miscellaneous stuff.
  You can find my firmware archive and other things @ <a href="https://cocaine.trade">cocaine.trade</a>
lang: en-US
timezone:  Europe/Rome
data-theme: dark # default theme "dark" | "light"
repo: ptrpaws/ptrpaws.github.io # site repo for utterances [optional]
comments-enabled: true # true to enable utterances comments, false to hide them

author:
  name: ellie
  avatar: https://pbs.twimg.com/profile_images/1614056067377274880/0br2M55j_400x400.png
  username: # general username
  github: ptrpaws # github username
  twitter: ptrpaws # twitter username
  mastodon: wetdry.world/@ptrpaws # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: blahaj564+site@gmail.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://blahaj.life" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug # /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


